---
name: "Make Release"

on:
  push:
    branches: [ main ]

jobs:
  pre-release:
    name: "Release"
    permissions: write-all
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          sudo dpkg --add-architecture i386 && sudo apt update && wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo apt install software-properties-common && sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu/ $(lsb_release -cs) main" && sudo apt update && sudo apt install --install-recommends winehq-stable && npm i --include-dev          
      - name: Build
        run: |
          npm run make && npx electron-builder -w -p never
      - name: "Release" 
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            out/make/*/*/*
            out/make/*.AppImage
            dist/*.exe
