---
name: "Make Release"

on:
  push:
    branches: [ main ]

jobs:
  pre-release:
    name: "Release"
    permissions: write-all
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          npm i --include-dev
      - name: Build
        run: |
          npm run make
      - name: "Release" 
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            out/make/*/*/*
